[/Script/EngineSettings.GeneralProjectSettings]
ProjectName=LAKOU LAKAY
ProjectVersion=0.1.0
CompanyName=
Description=Jeu coopératif en ligne (2 joueurs) - reconquête de quartiers et libération d'otages.

[/Script/UnrealEd.ProjectPackagingSettings]
Build=IfProjectHasCode
; Cartes à inclure dans le package (à compléter au fur et à mesure).
+MapsToCook=(FilePath="/Game/Maps/L_MainMenu")
+MapsToCook=(FilePath="/Game/Maps/L_Lakou_Hub")
